# Generated by Django 6.0.6 on 2026-06-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.CharField(max_length=25),
        ),
    ]
